server:
  port: 8080
spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:h2:mem:greendog
  h2:
    console:
      enabled: true
      path: /h2
  hateoas:
    use-hal-as-default-json-media-type: false
  jpa:
    show-sql: true
  profiles:
    active: dev
  thymeleaf:
    cache: false
